so the other half of the discussion I was hoping to have was, if "exceptions" don't require a restart and could be passed to the callback to avoid the performance hit of try/catch, shouldn't we be returning errors from sync methods then instead of throwing for the same reason