I've seen data get through even when connecting to an invalid cert with rejectUnauthoried: true