this function is called several times in a row. node is quitting without any error message when I include it and I can't figure out why.