well, it is wrapping the callbacks in a try-catch