Was having connection trouble - so I'll repeat. Apologies if I'm saying it twice. I'm trying to write a NodeJS native addon and when I require my module, I get "Error: no error" thrown. Anyone seen that before?