*maybe* a thrown Error stops that from ever happening (but it otherwise would). I'm not so sure if this is a good idea or not.