async calls the callback on first error instead of accumulating them - this is terrible :/