actually, no, don't assume close will be called after error