but try { redis = require('redis').createClient(); } catch(e) { } doesn't actually catch the error